{
  twitter {
    user (identifier: name, identity: "sebastiansoft") {
      created_at
      description
      id
      screen_name
      name
      tweets_count
      followers_count
      tweets(limit: 10) {
        id
        text
      }
    }
  }
}
